x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2023-09-23T03-47-50Z
  command: server --console-address ":9090" /mnt/data
  ports:
    - "9000:9000"
    - "9090:9090"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  minioc1:
    <<: *minio-common
    volumes:
      - ./minioc1-data:/mnt/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_VOLUMES: "/mnt/data"
    